System.register([], function(exports_1, context_1) {
    "use strict";
    var __moduleName = context_1 && context_1.id;
    var imageSize, ItemMap;
    return {
        setters:[],
        execute: function() {
            (function (imageSize) {
                imageSize[imageSize["sb"] = 0] = "sb";
                imageSize[imageSize["lg"] = 1] = "lg";
                imageSize[imageSize["full"] = 2] = "full";
            })(imageSize || (imageSize = {}));
            exports_1("imageSize", imageSize);
            ItemMap = (function () {
                function ItemMap() {
                    this.itemDict = {
                        '1': 'item_blink',
                        '2': 'item_blades_of_attack',
                        '3': 'item_broadsword',
                        '4': 'item_chainmail',
                        '5': 'item_claymore',
                        '6': 'item_helm_of_iron_will',
                        '7': 'item_javelin',
                        '8': 'item_mithril_hammer',
                        '9': 'item_platemail',
                        '10': 'item_quarterstaff',
                        '11': 'item_quelling_blade',
                        '12': 'item_ring_of_protection',
                        '13': 'item_gauntlets',
                        '14': 'item_slippers',
                        '15': 'item_mantle',
                        '16': 'item_branches',
                        '17': 'item_belt_of_strength',
                        '18': 'item_boots_of_elves',
                        '19': 'item_robe',
                        '20': 'item_circlet',
                        '21': 'item_ogre_axe',
                        '22': 'item_blade_of_alacrity',
                        '23': 'item_staff_of_wizardry',
                        '24': 'item_ultimate_orb',
                        '25': 'item_gloves',
                        '26': 'item_lifesteal',
                        '27': 'item_ring_of_regen',
                        '28': 'item_sobi_mask',
                        '29': 'item_boots',
                        '30': 'item_gem',
                        '31': 'item_cloak',
                        '32': 'item_talisman_of_evasion',
                        '33': 'item_cheese',
                        '34': 'item_magic_stick',
                        '35': 'item_recipe_magic_wand',
                        '36': 'item_magic_wand',
                        '37': 'item_ghost',
                        '38': 'item_clarity',
                        '39': 'item_flask',
                        '40': 'item_dust',
                        '41': 'item_bottle',
                        '42': 'item_ward_observer',
                        '43': 'item_ward_sentry',
                        '44': 'item_tango',
                        '45': 'item_courier',
                        '46': 'item_tpscroll',
                        '47': 'item_recipe_travel_boots',
                        '48': 'item_travel_boots',
                        '49': 'item_recipe_phase_boots',
                        '50': 'item_phase_boots',
                        '51': 'item_demon_edge',
                        '52': 'item_eagle',
                        '53': 'item_reaver',
                        '54': 'item_relic',
                        '55': 'item_hyperstone',
                        '56': 'item_ring_of_health',
                        '57': 'item_void_stone',
                        '58': 'item_mystic_staff',
                        '59': 'item_energy_booster',
                        '60': 'item_point_booster',
                        '61': 'item_vitality_booster',
                        '62': 'item_recipe_power_treads',
                        '63': 'item_power_treads',
                        '64': 'item_recipe_hand_of_midas',
                        '65': 'item_hand_of_midas',
                        '66': 'item_recipe_oblivion_staff',
                        '67': 'item_oblivion_staff',
                        '68': 'item_recipe_pers',
                        '69': 'item_pers',
                        '70': 'item_recipe_poor_mans_shield',
                        '71': 'item_poor_mans_shield',
                        '72': 'item_recipe_bracer',
                        '73': 'item_bracer',
                        '74': 'item_recipe_wraith_band',
                        '75': 'item_wraith_band',
                        '76': 'item_recipe_null_talisman',
                        '77': 'item_null_talisman',
                        '78': 'item_recipe_mekansm',
                        '79': 'item_mekansm',
                        '80': 'item_recipe_vladmir',
                        '81': 'item_vladmir',
                        '84': 'item_flying_courier',
                        '85': 'item_recipe_buckler',
                        '86': 'item_buckler',
                        '87': 'item_recipe_ring_of_basilius',
                        '88': 'item_ring_of_basilius',
                        '89': 'item_recipe_pipe',
                        '90': 'item_pipe',
                        '91': 'item_recipe_urn_of_shadows',
                        '92': 'item_urn_of_shadows',
                        '93': 'item_recipe_headdress',
                        '94': 'item_headdress',
                        '95': 'item_recipe_sheepstick',
                        '96': 'item_sheepstick',
                        '97': 'item_recipe_orchid',
                        '98': 'item_orchid',
                        '99': 'item_recipe_cyclone',
                        '100': 'item_cyclone',
                        '101': 'item_recipe_force_staff',
                        '102': 'item_force_staff',
                        '103': 'item_recipe_dagon',
                        '104': 'item_dagon',
                        '105': 'item_recipe_necronomicon',
                        '106': 'item_necronomicon',
                        '107': 'item_recipe_ultimate_scepter',
                        '108': 'item_ultimate_scepter',
                        '109': 'item_recipe_refresher',
                        '110': 'item_refresher',
                        '111': 'item_recipe_assault',
                        '112': 'item_assault',
                        '113': 'item_recipe_heart',
                        '114': 'item_heart',
                        '115': 'item_recipe_black_king_bar',
                        '116': 'item_black_king_bar',
                        '117': 'item_aegis',
                        '118': 'item_recipe_shivas_guard',
                        '119': 'item_shivas_guard',
                        '120': 'item_recipe_bloodstone',
                        '121': 'item_bloodstone',
                        '122': 'item_recipe_sphere',
                        '123': 'item_sphere',
                        '124': 'item_recipe_vanguard',
                        '125': 'item_vanguard',
                        '126': 'item_recipe_blade_mail',
                        '127': 'item_blade_mail',
                        '128': 'item_recipe_soul_booster',
                        '129': 'item_soul_booster',
                        '130': 'item_recipe_hood_of_defiance',
                        '131': 'item_hood_of_defiance',
                        '132': 'item_recipe_rapier',
                        '133': 'item_rapier',
                        '134': 'item_recipe_monkey_king_bar',
                        '135': 'item_monkey_king_bar',
                        '136': 'item_recipe_radiance',
                        '137': 'item_radiance',
                        '138': 'item_recipe_butterfly',
                        '139': 'item_butterfly',
                        '140': 'item_recipe_greater_crit',
                        '141': 'item_greater_crit',
                        '142': 'item_recipe_basher',
                        '143': 'item_basher',
                        '144': 'item_recipe_bfury',
                        '145': 'item_bfury',
                        '146': 'item_recipe_manta',
                        '147': 'item_manta',
                        '148': 'item_recipe_lesser_crit',
                        '149': 'item_lesser_crit',
                        '150': 'item_recipe_armlet',
                        '151': 'item_armlet',
                        '152': 'item_invis_sword',
                        '153': 'item_recipe_sange_and_yasha',
                        '154': 'item_sange_and_yasha',
                        '155': 'item_recipe_satanic',
                        '156': 'item_satanic',
                        '157': 'item_recipe_mjollnir',
                        '158': 'item_mjollnir',
                        '159': 'item_recipe_skadi',
                        '160': 'item_skadi',
                        '161': 'item_recipe_sange',
                        '162': 'item_sange',
                        '163': 'item_recipe_helm_of_the_dominator',
                        '164': 'item_helm_of_the_dominator',
                        '165': 'item_recipe_maelstrom',
                        '166': 'item_maelstrom',
                        '167': 'item_recipe_desolator',
                        '168': 'item_desolator',
                        '169': 'item_recipe_yasha',
                        '170': 'item_yasha',
                        '171': 'item_recipe_mask_of_madness',
                        '172': 'item_mask_of_madness',
                        '173': 'item_recipe_diffusal_blade',
                        '174': 'item_diffusal_blade',
                        '175': 'item_recipe_ethereal_blade',
                        '176': 'item_ethereal_blade',
                        '177': 'item_recipe_soul_ring',
                        '178': 'item_soul_ring',
                        '179': 'item_recipe_arcane_boots',
                        '180': 'item_arcane_boots',
                        '181': 'item_orb_of_venom',
                        '182': 'item_stout_shield',
                        '183': 'item_recipe_invis_sword',
                        '184': 'item_recipe_ancient_janggo',
                        '185': 'item_ancient_janggo',
                        '186': 'item_recipe_medallion_of_courage',
                        '187': 'item_medallion_of_courage',
                        '188': 'item_smoke_of_deceit',
                        '189': 'item_recipe_veil_of_discord',
                        '190': 'item_veil_of_discord',
                        '191': 'item_recipe_necronomicon_2',
                        '192': 'item_recipe_necronomicon_3',
                        '193': 'item_necronomicon_2',
                        '194': 'item_necronomicon_3',
                        '195': 'item_recipe_diffusal_blade_2',
                        '196': 'item_diffusal_blade_2',
                        '197': 'item_recipe_dagon_2',
                        '198': 'item_recipe_dagon_3',
                        '199': 'item_recipe_dagon_4',
                        '200': 'item_recipe_dagon_5',
                        '201': 'item_dagon_2',
                        '202': 'item_dagon_3',
                        '203': 'item_dagon_4',
                        '204': 'item_dagon_5',
                        '205': 'item_recipe_rod_of_atos',
                        '206': 'item_rod_of_atos',
                        '207': 'item_recipe_abyssal_blade',
                        '208': 'item_abyssal_blade',
                        '209': 'item_recipe_heavens_halberd',
                        '210': 'item_heavens_halberd',
                        '211': 'item_recipe_ring_of_aquila',
                        '212': 'item_ring_of_aquila',
                        '213': 'item_recipe_tranquil_boots',
                        '214': 'item_tranquil_boots',
                        '215': 'item_shadow_amulet',
                        '216': 'item_enchanted_mango',
                        '217': 'item_recipe_ward_dispenser',
                        '218': 'item_ward_dispenser',
                        '219': 'item_recipe_travel_boots_2',
                        '220': 'item_travel_boots_2',
                        '221': 'item_recipe_lotus_orb',
                        '226': 'item_lotus_orb',
                        '227': 'item_recipe_solar_crest',
                        '228': 'item_recipe_octarine_core',
                        '229': 'item_solar_crest',
                        '230': 'item_recipe_guardian_greaves',
                        '231': 'item_guardian_greaves',
                        '235': 'item_octarine_core',
                        '241': 'item_tango_single',
                        '242': 'item_crimson_guard',
                        '243': 'item_recipe_crimson_guard',
                        '246': 'item_recipe_moon_shard',
                        '247': 'item_moon_shard',
                        '248': 'item_recipe_silver_edge',
                        '249': 'item_silver_edge',
                        '253': 'item_recipe_glimmer_cape',
                        '254': 'item_glimmer_cape',
                        '1000': 'item_halloween_candy_corn',
                        '1001': 'item_mystery_hook',
                        '1002': 'item_mystery_arrow',
                        '1003': 'item_mystery_missile',
                        '1004': 'item_mystery_toss',
                        '1005': 'item_mystery_vacuum',
                        '1006': 'item_halloween_rapier',
                        '1007': 'item_greevil_whistle',
                        '1008': 'item_greevil_whistle_toggle',
                        '1009': 'item_present',
                        '1010': 'item_winter_stocking',
                        '1011': 'item_winter_skates',
                        '1012': 'item_winter_cake',
                        '1013': 'item_winter_cookie',
                        '1014': 'item_winter_coco',
                        '1015': 'item_winter_ham',
                        '1016': 'item_winter_kringle',
                        '1017': 'item_winter_mushroom',
                        '1018': 'item_winter_greevil_treat',
                        '1019': 'item_winter_greevil_garbage',
                        '1020': 'item_winter_greevil_chewy'
                    };
                }
                ItemMap.prototype.getItemById = function (id) {
                    return this.itemDict[id];
                };
                ItemMap.prototype.getHeroIdByString = function (heroName) {
                    var heroes = this.itemDict;
                    for (var prop in heroes) {
                        if (heroes.hasOwnProperty(prop)) {
                            if (heroes[prop] === heroName)
                                return prop;
                        }
                    }
                    return '-1';
                };
                ItemMap.prototype.toPhotoString = function (itemId, size, itemName) {
                    if (!itemName)
                        itemId = this.getItemById(itemId);
                    return itemId.replace(/(item_)/g, '') + '_' + imageSize[size] + '.png';
                };
                ItemMap.HERO_IMG_BASE_URL = 'http://cdn.dota2.com/apps/dota2/images/items/';
                return ItemMap;
            }());
            exports_1("ItemMap", ItemMap);
        }
    }
});
//# sourceMappingURL=dotaItemMap.service.js.map